src/accounts/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url, patterns


urlpatterns = patterns('django.contrib.auth.views',
    url(r'^login/$', 'login', {'template_name': 'accounts/login.html'}, 'login'),
)

urlpatterns += patterns('src.accounts.views',
    url(r'^create/$', 'create', name='create'),
    url(r'^logout', 'logout', name='logout'),
    url(r'^confirm_email/(?P<confirmation_key>\w+)/$', 'confirm_email', name='confirm_email'),
    url(r'^password_reset/$', 'password_reset', name='password_reset'),
    url(r'^password_reset_confirm/(?P<uidb36>\w+)/(?P<token>[\w\-]+)$', 'password_reset_confirm', name='password_reset_confirm'),
    url(r'^profile/(?P<user_pk>\d+)/$', 'profile', name='profile'),
    url(r'^edit/$', 'edit', name='edit'),
)

src/urls.py
# -*- coding: utf-8

from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'', include('social_auth.urls')),
    url(r'^', include('src.main.urls', 'main')),
    url(r'^admin/', include(admin.site.urls)),
    # url(r'^lessons/', include('src.lessons.urls', 'lessons')),
    url(r'^problems/', include('src.problems.urls', 'problems')),
    url(r'^auth/', include('src.accounts.urls', 'accounts')),
    url(r'^achievments/', include('src.achievments.urls', 'achievments')),
    url(r'^challenge/', include('src.challenge.urls', 'challenges')),
    url(r'^game/', include('src.games.urls', 'games')),
)+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/lessons/models.py
# -*- coding: utf-8 -*-

from django.db import models


class Theme(models.Model):
    title = models.CharField(verbose_name=u'Название темы', max_length=150)
    description = models.TextField(verbose_name=u'Описание', blank=True)
    klass = models.IntegerField(verbose_name=u'Класс')
    sort_number = models.IntegerField(u'Номер темы по списку')
    complit_count = models.IntegerField(u'Количество прошедших', default=0)

    class Meta:
        verbose_name = u'Тема'
        verbose_name_plural = u'Темы'

    def __unicode__(self):
        return self.title


class Lesson(models.Model):
    theme = models.ForeignKey(Theme, verbose_name=u'Тема')
    number = models.IntegerField(verbose_name=u'Номер урока')
    title = models.CharField(verbose_name=u'Название', max_length=150)
    material = models.TextField(verbose_name=u'Учебный материал')
    test = models.BooleanField(verbose_name=u'Контрольная работа', default=False)


    class Meta:
        verbose_name = u'Урок'
        verbose_name_plural = u'Уроки'

    def __unicode__(self):
        return self.title


class Task(models.Model):
    lesson = models.ForeignKey(Lesson, verbose_name=u'Урок')
    text = models.TextField(verbose_name=u'Текст задания')
    answer = models.CharField(verbose_name=u'Ответ', max_length=150)
    slog = models.IntegerField(verbose_name=u'Сложность',
                               help_text=u'От 1 до 3', default='1')

    class Meta:
        verbose_name = u'Задание'
        verbose_name_plural = u'Задания'

    def __unicode__(self):
        return self.text[:20]


class Remember(models.Model):
    title = models.CharField(verbose_name=u'Заголовок', max_length=150, blank=True)
    text =models.TextField(verbose_name=u'Текст')
    lesson = models.ForeignKey(Lesson, verbose_name=u'К уроку...')

    class Meta:
        verbose_name = u'Запоминалка'
        verbose_name_plural = u'Запоминалки'

    def __unicode__(self):
        return self.title

src/problems/models.py
# -*- coding: utf-8 -*-

from mptt.models import MPTTModel, TreeForeignKey
from django.db import models

class Category(MPTTModel):
    title = models.CharField(verbose_name=u'Название категории', max_length=200)
    slug = models.SlugField(verbose_name=u'Ссылка', unique=True)
    description = models.TextField(verbose_name=u'Описание', blank=True)
    sort_number = models.IntegerField(verbose_name=u'Номер по порядку', default=0)
    parent = TreeForeignKey('self', verbose_name=u'Родительская категория',
                            related_name='children', blank=True,
                            help_text=u'Родителеьская категория для данной категории', null=True)

    class MPTTMeta:
        order_insertion_by = ['sort_number']

    class Meta:
        verbose_name = u'Категория задач'
        verbose_name_plural = u'Категории задач'

    def __unicode__(self):
        return self.title


class Problem(models.Model):
    slogn = models.IntegerField(verbose_name=u'Сложность', help_text=u'От 1 до 3', default=1)
    text = models.TextField(verbose_name=u'Текст')
    answer = models.CharField(verbose_name=u'Ответ', max_length=150)
    category = models.ForeignKey(Category, verbose_name=u'Относится к категории')
    klass =  models.IntegerField(verbose_name=u'Класс', blank=True, null=True)
    ist = models.CharField(verbose_name=u'Источник', max_length = 50, blank=True)
    date_add = models.DateTimeField(auto_now_add=True)
    rating = models.IntegerField(verbose_name=u'Рейтинг задачи', default=0)
    solved = models.IntegerField(verbose_name=u'Количество решивших', default=0)
    number = models.IntegerField(verbose_name=u'Номер задачи', default=0, blank=True)

    class Meta:
        verbose_name = u'Задача'
        verbose_name_plural = u'Задачи'

    def __unicode__(self):
        return self.text[:80]

    @models.permalink
    def get_absolute_url(self):
        return ('problems:problem', (), {'problem_pk': self.pk})

    def inc_solved(self):
        self.solved += 1
        self.save()

    def inc_rating(self):
        self.rating += 1
        self.save()

    def dec_rating(self):
        self.rating -= 1
        self.save()

    def set_number(self, n):
        self.number = n
        self.save()


class Variant(models.Model):
    pro = models.ForeignKey(Problem, verbose_name=u'Задача')
    nam = models.CharField(verbose_name=u'Название', help_text=u'A, B, C, ...', max_length=2)
    val = models.CharField(verbose_name=u'Значение', help_text=u'Строка, число, картинка', max_length=250)
    tru = models.BooleanField(verbose_name=u'Правильный?', default=False)

    class Meta:
        verbose_name = u'Вариант ответа'
        verbose_name_plural = u'Варианты ответов'
        ordering = ('nam',)

    def __unicode__(self):
        return '%s %s' % (self.nam, self.val)

src/accounts/forms.py
# -*- coding: utf-8 -*-

from django.contrib.auth.forms import UserChangeForm, UserCreationForm, PasswordResetForm as AuthPasswordResetForm
from django.contrib.auth.tokens import default_token_generator
from django.contrib.sites.models import get_current_site
from django.utils.http import int_to_base36
from django import forms
from yacaptcha.fields import YaCaptchaField

from .models import User
from src.mail import send_templated_email


class AdminUserAddForm(UserCreationForm):

    class Meta:
        model = User

    def clean_username(self):
        # Since User.username is unique, this check is redundant,
        # but it sets a nicer error message than the ORM. See #13147.
        username = self.cleaned_data["username"]
        try:
            User._default_manager.get(username=username)
        except User.DoesNotExist:
            return username
        raise forms.ValidationError(self.error_messages['duplicate_username'])


class AdminUserChangeForm(UserChangeForm):

    class Meta:
        model = User


class CreateUserForm(forms.ModelForm):
    error_messages = {
        'duplicate_email': u"Пользователь с таким адресом электронной почты уже существует",
        'duplicate_username': u"Пользователь с таким логином уже существует",
        'password_mismatch': u"Введенные пароли не совпадают",
    }

    password1 = forms.CharField(label="Пароль",
                                widget=forms.PasswordInput)
    password2 = forms.CharField(label="Повторите пароль",
                                widget=forms.PasswordInput,
                                help_text="Введите пароль еще раз, чтобы не ошибиться")
    captcha = YaCaptchaField(label=u'Введите символы с картинки')

    class Meta:
        model = User
        fields = ('username', 'password1', 'password2', 'email')

    def clean_email(self):
        email = self.cleaned_data["email"]
        if email:
            try:
                User._default_manager.get(email=email)
            except User.DoesNotExist:
                return email
            raise forms.ValidationError(self.error_messages['duplicate_email'])

    def clean_username(self):
        username = self.cleaned_data["username"]
        try:
            User._default_manager.get(username=username)
        except User.DoesNotExist:
            return username
        raise forms.ValidationError(self.error_messages['duplicate_username'])

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'])
        return password2

    def save(self, commit=True):
        user = super(CreateUserForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserEditForm(forms.ModelForm):
    current_password = forms.CharField(label=u'Текущий пароль', widget=forms.PasswordInput, required=False,
                                       help_text=u'Введите Ваш текущий пароль, чтобы его изменить')
    current_password.widget.attrs.update({'autocomplit': 'off'})
    new_password = forms.CharField(label=u'Новый пароль', widget=forms.PasswordInput, required=False)
    new_password_verify = forms.CharField(label=u'Повторите новый пароль', widget=forms.PasswordInput,
                                          required=False)

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email',)

    def clean(self):
        current, new, verify = map(self.cleaned_data.get,
                                   ('current_password', 'new_password', 'new_password_verify'))
        if current and self.instance.has_usable_password() and not self.instance.check_password(current):
            raise forms.ValidationError(u'Неправильный пароль')
        if new and new != verify:
            raise forms.ValidationError(u'Пароли не совпадают')
        return self.cleaned_data

    def clean_email(self):
        value = self.cleaned_data['email']
        if value:
            try:
                User.objects.exclude(pk=self.instance.pk).get(email=value)
                raise forms.ValidationError(u'Этот адрес электронной почты уже используется')
            except User.DoesNotExist:
                pass
        return value

    def save(self, commit=True):
        password = self.cleaned_data.get('new_password')
        if password:
            self.instance.set_password(password)
        return super(UserEditForm, self).save(commit)


class PasswordResetForm(AuthPasswordResetForm):

    def clean_email(self):
        email = self.cleaned_data["email"]
        self.users_cache = User.objects.filter(
            email__iexact=email,
            is_active=True,
            is_valid_email=True
        )
        if len(self.users_cache) == 0:
            raise forms.ValidationError(u"Указанный электронный адрес не найден. Вы уверены, что зарегистрировались и подтвердили электронный адрес?")
        return email

    def save(self, domain_override=None, email_template_name='accounts/password_reset_email.html',
             use_https=False, token_generator=default_token_generator, from_email=None, request=None, **kwargs):
        """
        Generates a one-use only link for resetting password and sends to the user
        """
        for user in self.users_cache:
            if not domain_override:
                current_site = get_current_site(request)
                site_name = current_site.name
                domain = current_site.domain
            else:
                site_name = domain = domain_override

            c = {
                'email': user.email,
                'domain': domain,
                'site_name': site_name,
                'uid': int_to_base36(user.id),
                'user': user,
                'token': token_generator.make_token(user),
                'protocol': use_https and 'https' or 'http',
                }
            subject = u"Смена пароля для %s" % site_name
            send_templated_email([user.email], subject, email_template_name, c, from_email)

src/accounts/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import redirect, get_object_or_404
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib import messages
from django.contrib.auth import REDIRECT_FIELD_NAME
from django.contrib.auth.views import password_reset as auth_password_reset, password_reset_confirm as auth_password_reset_confirm
from django.contrib.auth.decorators import login_required

from src.decorators import render_to, to_list
from .forms import CreateUserForm, PasswordResetForm, UserEditForm
from .models import User, EmailConfirmation
from src.problems.models import Category, Problem
from src.lessons.models import Theme
from src.achievments.models import Achievment


@render_to('accounts/create.html')
def create(request):
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, u'Учетная запись создана! На указанный почтовый адрес отправлено письмо с подтверждением. Пожалуйста, проверьте почту.')
            return redirect('accounts:login')
        messages.error(request, u'Пожалуйста, исправьте ошибки и отправьте форму еще раз.')
    else:
        form = CreateUserForm()
    return {
        'form': form
    }


def logout(request):
    from django.contrib.auth import logout
    logout(request)
    redirect_to = request.REQUEST.get(REDIRECT_FIELD_NAME, '/')
    return redirect(redirect_to)


def confirm_email(request, confirmation_key):
    confirmation_key = confirmation_key.lower()
    user = EmailConfirmation.objects.confirm_email(confirmation_key)

    if not user:
        messages.error(request, u'Ссылка с кодом подтверждения не действительна.')
        return redirect('/')
    else:
        messages.success(request, u'Электронная почта подтверждена.')
        return redirect('/auth/login/')


def password_reset(request):
    response = auth_password_reset(request,
                                   template_name='accounts/password_reset.html',
                                   email_template_name='accounts/password_reset_email.html',
                                   password_reset_form=PasswordResetForm,
                                   post_reset_redirect='/')

    if isinstance(response, HttpResponseRedirect):
        messages.success(request, u'На Ваш адрес электронной почты отправлено письмо с инструкцией по изменению пароля.')
        return response

    return response


def password_reset_confirm(request, uidb36, token):
    return auth_password_reset_confirm(request, uidb36, token,
                                       post_reset_redirect=reverse('accounts:password_reset_complete'),
                                       template_name='accounts/password_reset_confirm.html'
    )


@render_to('accounts/profile.html')
def profile(request, user_pk):
    user_obj = get_object_or_404(User, pk=user_pk)

    # Задачи
    all_cat = Category.objects.all()
    categories = []
    for category in all_cat:
        if category.parent: continue
        categories.append([category, to_list(category.get_children(), 3)])
    solved_progress = int(float(len(user_obj.userprogress.problems_solved_problems.all())) / float(len(Problem.objects.all())) * 100)

    #Уроки
    themes = [[i + 5, Theme.objects.filter(klass=(i+5))] for i in range(7)]

    #Испытания
    chall_cat = [cb.category for cb in user_obj.userprogress.challenge_best.all()]
    challenge_categories = {'kenguru': Category.objects.get(slug='kenguru').get_children(),
                            'olimpiada': Category.objects.get(slug='olimpiada').get_children()}

    #Избранное
    favorite_problems = user_obj.favorite_problems.all()

    #Достижения
    achievments = Achievment.objects.all()

    return {'categories': categories, 'user_obj': user_obj, 'solved_progress': solved_progress, 'pr_count': len(Problem.objects.all()),
            'themes': themes,
            'chall_cat': chall_cat,
            'favorites': favorite_problems,
            'achievments': achievments,
            'challenge_categories': challenge_categories}


@render_to('accounts/edit.html')
@login_required
def edit(request):
    if request.method == 'POST':
        form = UserEditForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, u'Профиль успешно сохранен! Подтвердите адрес электронной почты, если он был изменен.')
            return redirect('accounts:profile', request.user.pk)
        messages.error(request, u'Пожалуйста, исправьте ошибки.')
    else:
        form = UserEditForm(instance=request.user)
    return {'form': form}

src/accounts/templates/accounts/base_accounts.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                {% if messages%}
                    <ul class="messages">
                        {% for message in messages %}
                            <li><div {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>
                                <a class="close" data-dismiss="alert">&times;</a>
                                {{ message }}
                            </div>
                            </li>
                        {% endfor %}
                    </ul>
                {% endif %}
                {% block content_accounts %}{% endblock %}
            </div>
        </div>
    </div>
{% endblock %}

src/accounts/templates/accounts/create.html
{% extends 'accounts/base_accounts.html' %}
{% load bootstrap %}

{% block title %}Регистрация - Math Challenge{% endblock %}

{% block content_accounts %}
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            {% if user.is_authenticated %}
                <div class="alert alert-info">
                    <p>Вы уже авторизованы.</p>
                </div>
            {% else %}
                <form class='' method="post">{% csrf_token %}
                    <legend>Регистрация</legend>
                    <fieldset>
                        {{ form|bootstrap }}
                    </fieldset>
                    <button class="btn btn-block btn-success margin-bottom-20" type="submit">Регистрация</button>
                    <small class='text-muted'>Уже зарегистрированы? <a href="{% url 'accounts:login' %}">Входите</a></small>
                </form>
            {% endif %}
        </div>
    </div>
{% endblock %}

src/accounts/templates/accounts/edit.html
{% extends 'accounts/base_accounts.html' %}
{% load bootstrap %}

{% block title %}{{ user.get_full_name }} - Изменение профиля{% endblock %}

{% block content_accounts %}
    <div class="col-md-4 col-md-offset-4">
        <form method="post">{% csrf_token %}
                <img class="img-circle pull-left margin-right-20" src={{ user.avatar }}>
                <h2 class="clearfix">{{ user.get_full_name }}</h2>
            <fieldset>
                {{ form|bootstrap }}
            </fieldset>
            <button class="btn btn-success btn-block" type="submit">Сохранить изменения</button>
        </form>
    </div>
{% endblock %}

src/accounts/templates/accounts/email_confirmation_message.html
{% load i18n %}{% blocktrans with current_site.name as site_name and user.email as email %}
<p>Вы зарегистрировались на сайте {{ site_name }}.</p>

<p>Для активации аккаунта перейдите по ссылке <a href="{{ activate_url }}">{{ activate_url }}</a>.</p>

<p>Если вы не регистировались на нашем сайте, проигнорируйте это письмо.</p>

<p>{{ site_name }}</p>
{% endblocktrans %}

src/accounts/templates/accounts/profile.html
{% extends 'accounts/base_accounts.html' %}
{% load problems_tag lessons_tags achievments_tags challenge_tags %}

{% block title %}{{ user_obj.get_full_name }}, профиль пользователя - Math Challenge{% endblock %}

{% block content_accounts %}
    <div class="row" xmlns="http://www.w3.org/1999/html">
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-4 col-md-offset-4 margin-bottom-20">
                    <img class="img-circle pull-left margin-right-20" src={{ user_obj.avatar }}>
                    <h4 class="margin-top-20">{{ user_obj.get_full_name }}</h4>
                    <span class="clearfix">Решено {{ user_obj.userprogress.problems_solved_problems.all|length }} задач из {{ pr_count }} ({{ user_obj.get_points }} <i class="fa fa-money"></i>)</span>
                </div>
            </div>
            {% if user == user_obj %}
                <a href="{% url 'accounts:edit' %}" class="btn btn-primary pull-right">Изменить</a>
                <ul class="nav nav-tabs">
{#                    <li class="active"><a href="#lessons" data-toggle="tab"><strong><i class="fa fa-book"></i> Уроки</strong></a></li>#}
                    <li class="active"><a href="#problems" data-toggle="tab"><strong><i class="fa fa-question-circle"></i> Задачи</strong></a></li>
                    <li><a href="#challenge" data-toggle="tab"><strong><i class="fa fa-bolt"></i> Испытания</strong></a></li>
                    <li><a href="#favorites" data-toggle="tab"><strong><i class="fa fa-heart"></i> Избранное</strong></a></li>
                    <li><a href="#achienments" data-toggle="tab"><strong><i class="fa fa-certificate"></i> Достижения</strong></a></li>
                </ul>

                <!-- Tab panes -->
                <div class="tab-content">
{#                    <div class="tab-pane fade in active" id="lessons">#}
{#                        <table class="table table-bordered table-striped margin-top-20">#}
{#                            <thead>#}
{#                                <tr>#}
{#                                    <th>Название темы</th>#}
{#                                    <th>Описание</th>#}
{#                                    <th colspan="2">Прогресс</th>#}
{#                                </tr>#}
{#                            </thead>#}
{#                            <tbody>#}
{#                                {% for th in themes %}{% if th.1 %}#}
{#                                    <tr>#}
{#                                        <td colspan="4">{{ th.0 }} класс</td>#}
{#                                    </tr>#}
{#                                    {% for theme in th.1 %}#}
{#                                        <tr>#}
{#                                            <td><a href="{% url 'lessons:theme' theme.pk %}">{{ theme.title }}</a></td>#}
{#                                            <td>{{ theme.description }}</td>#}
{#                                            <td style="width: 15%">#}
{#                                                <div class="progress">#}
{#                                                    <div class="progress-bar{% if user|get_theme_progress:theme == 100 %} progress-bar-success{% endif %}" role="progressbar" style="width: {{ user|get_theme_progress:theme }}%;"></div>#}
{#                                                </div>#}
{#                                            </td>#}
{#                                            <td style="width: 5%; white-space: nowrap">{{ user|get_lesson_progress:theme }} / {{ theme.lesson_set.all|length }}</td>#}
{#                                        </tr>#}
{#                                    {% endfor %}#}
{#                                    {% endif %}#}
{#                                {% endfor %}#}
{#                            </tbody>#}
{#                        </table>#}
{#                    </div>#}

                    <div class="tab-pane fade in active" id="problems">
                        <div class="progress margin-top-20 text-center">
                            <div class="progress-bar" role="progressbar" aria-valuenow="{{ solved_progress }}" aria-valuemin="0" aria-valuemax="100" style="width: {{ solved_progress }}%;">
                                <span class="progress_bar_text">Решено {{ user.userprogress.problems_solved_problems.all|length }} из {{ pr_count }} задач</span>
                            </div>
                        </div>
                        {% for cat in categories %}
                            <div class="panel panel-primary" style="min-width: 1000px">
                                <div class="panel-heading">{{ cat.0.title }}</div>
{#                                Список подкатегорий данной категории #}
                                {% for l in cat.1 %}
                                    {% for c in l %}
                                        <div class="problems_cat_container">
                                            <div class="title">{{ c.title }}</div>
                                            <div class="body">
                                                {% tables c.problem_set.all %}
                                            </div>
                                        </div>
                                    {% endfor %}
                                    <div class="clearfix"></div>
                                {% endfor %}
                            </div>
                        {% endfor %}
                    </div>

                    <div class="tab-pane fade" id="challenge">
                        <div class="margin-top-20"></div>
{#                        <h3>Лучшие результаты испытаний</h3>#}
                        <h4>Кенгуру</h4>
                        {% for c in challenge_categories.kenguru %}
                            <div class="best_res">
                                <div class="best_res_title">{{ c.title }}</div>
                                    {% if c in chall_cat %}
                                        {% for cb in user.userprogress.challenge_best.all %}
                                            {% if c == cb.category %}
                                                <div class="best_res_result {{ cb.result|kenguru_result:c.slug }}"> {{ cb.result }}</div>
                                                <a class="btn btn-primary challenge_go" href="{% url 'challenges:challenge' c.slug %}">Пройти еще раз</a>
                                            {% endif %}
                                        {% endfor %}
                                    {% else %}
                                        <div class="best_res_result">&nbsp;-</div>
                                        <a class="btn btn-primary challenge_go" href="{% url 'challenges:challenge' c.slug %}">Пройти</a>
                                    {% endif %}
                                <div class="clearfix"></div>
                            </div>
                        {% endfor %}
                        <h4>Олимпиада</h4>
                        {% for c in challenge_categories.olimpiada %}
                            <div class="best_res">
                                <div class="best_res_title">{{ c.title }}</div>
                                {% if c in chall_cat %}
                                    {% for cb in user.userprogress.challenge_best.all %}
                                        {% if c == cb.category %}
                                            <div class="best_res_result {{ cb.result|kenguru_result:c.slug }}"> {{ cb.result }}</div>
                                            <a class="btn btn-primary challenge_go" href="{% url 'challenges:challenge' c.slug %}">Пройти еще раз</a>
                                        {% endif %}
                                    {% endfor %}
                                {% else %}
                                    <div class="best_res_result">&nbsp;-</div>
                                    <a class="btn btn-primary challenge_go" href="{% url 'challenges:challenge' c.slug %}">Пройти</a>
                                {% endif %}
                                <div class="clearfix"></div>
                            </div>
                        {% endfor %}
                    </div>

                    <div class="tab-pane fade" id="favorites">
                        <div class="margin-top-20"></div>
                        {% for pr in favorites %}
                            <div class="alert alert-warning" style="box-shadow: 1px 1px 2px grey">
                                <a class="close" data-dismiss="alert" href="{% url 'problems:add_fav' pr.pk %}" title="Убрать с избранного">&times;</a>
                                <div class="text-muted" style="padding: 4px 0 8px 0;">
                                    {{ pr.category.parent.title }} - <a href="{% url 'problems:category' pr.category.slug %}" class="text-muted">{{ pr.category.title }}</a> - Задача №{{ pr.number }}
                                    {% if pr in user.userprogress.problems_solved_problems.all %} <i class="fa fa-check grey-color" title="Задача решена"></i>{% endif %}
                                </div>
                                {{ pr.text|safe }}
                                <p class="text-right"><a href="{% url 'problems:problem' pr.pk %}">Перейти к задаче</a></p>
                            </div>
                        {% empty %}
                            <div class="alert alert-info">У вас пока нет избранных задач.</div>
                        {% endfor %}
                    </div>

                    <div class="tab-pane fade" id="achienments">
                        <div class="margin-top-20"></div>
                        {% for ach in user.userprogress.achievments.all %}
                            {% achievment ach.pk %}
                        {% empty %}
                            <div class="alert alert-info">
                                <p>Вы еще не получили ни одного достижения.</p>
                            </div>
                        {% endfor %}
{#                        {% for ach in achievments %}#}
{#                            {% if not ach in user.userprogress.achievments.all %}#}
{#                                {% achievment ach.pk %}#}
{#                            {% endif %}#}
{#                        {% endfor %}#}
                        <p><a href="{% url 'achievments:index' %}">Все достижения</a></p>
                    </div>
                </div>
            {% else %}

            {% endif %}
        </div>
    </div>
{% endblock %}