src/challenge/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, url


urlpatterns = patterns('src.challenge.views',
    url(r'^$', 'index', name='index'),
    url(r'^challenge_change/$', 'challenge_change'),
    url(r'^kenguru_check/$', 'kenguru_check'),
    url(r'^olimpiada_check/$', 'olimpiada_check'),
    url(r'^(?P<category_slug>\w+)/$', 'challenge', name='challenge'),
)

src/urls.py
# -*- coding: utf-8

from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'', include('social_auth.urls')),
    url(r'^', include('src.main.urls', 'main')),
    url(r'^admin/', include(admin.site.urls)),
    # url(r'^lessons/', include('src.lessons.urls', 'lessons')),
    url(r'^problems/', include('src.problems.urls', 'problems')),
    url(r'^auth/', include('src.accounts.urls', 'accounts')),
    url(r'^achievments/', include('src.achievments.urls', 'achievments')),
    url(r'^challenge/', include('src.challenge.urls', 'challenges')),
    url(r'^game/', include('src.games.urls', 'games')),
)+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/problems/models.py
# -*- coding: utf-8 -*-

from mptt.models import MPTTModel, TreeForeignKey
from django.db import models

class Category(MPTTModel):
    title = models.CharField(verbose_name=u'Название категории', max_length=200)
    slug = models.SlugField(verbose_name=u'Ссылка', unique=True)
    description = models.TextField(verbose_name=u'Описание', blank=True)
    sort_number = models.IntegerField(verbose_name=u'Номер по порядку', default=0)
    parent = TreeForeignKey('self', verbose_name=u'Родительская категория',
                            related_name='children', blank=True,
                            help_text=u'Родителеьская категория для данной категории', null=True)

    class MPTTMeta:
        order_insertion_by = ['sort_number']

    class Meta:
        verbose_name = u'Категория задач'
        verbose_name_plural = u'Категории задач'

    def __unicode__(self):
        return self.title


class Problem(models.Model):
    slogn = models.IntegerField(verbose_name=u'Сложность', help_text=u'От 1 до 3', default=1)
    text = models.TextField(verbose_name=u'Текст')
    answer = models.CharField(verbose_name=u'Ответ', max_length=150)
    category = models.ForeignKey(Category, verbose_name=u'Относится к категории')
    klass =  models.IntegerField(verbose_name=u'Класс', blank=True, null=True)
    ist = models.CharField(verbose_name=u'Источник', max_length = 50, blank=True)
    date_add = models.DateTimeField(auto_now_add=True)
    rating = models.IntegerField(verbose_name=u'Рейтинг задачи', default=0)
    solved = models.IntegerField(verbose_name=u'Количество решивших', default=0)
    number = models.IntegerField(verbose_name=u'Номер задачи', default=0, blank=True)

    class Meta:
        verbose_name = u'Задача'
        verbose_name_plural = u'Задачи'

    def __unicode__(self):
        return self.text[:80]

    @models.permalink
    def get_absolute_url(self):
        return ('problems:problem', (), {'problem_pk': self.pk})

    def inc_solved(self):
        self.solved += 1
        self.save()

    def inc_rating(self):
        self.rating += 1
        self.save()

    def dec_rating(self):
        self.rating -= 1
        self.save()

    def set_number(self, n):
        self.number = n
        self.save()


class Variant(models.Model):
    pro = models.ForeignKey(Problem, verbose_name=u'Задача')
    nam = models.CharField(verbose_name=u'Название', help_text=u'A, B, C, ...', max_length=2)
    val = models.CharField(verbose_name=u'Значение', help_text=u'Строка, число, картинка', max_length=250)
    tru = models.BooleanField(verbose_name=u'Правильный?', default=False)

    class Meta:
        verbose_name = u'Вариант ответа'
        verbose_name_plural = u'Варианты ответов'
        ordering = ('nam',)

    def __unicode__(self):
        return '%s %s' % (self.nam, self.val)

src/challenge/forms.py
# -*- coding: utf-8 -*-

from django import forms

src/challenge/views.py
# -*- coding: utf-8 -*-


import random
from django.shortcuts import get_object_or_404, render_to_response
from django.http import HttpResponseRedirect, Http404, HttpResponse
from django.core.urlresolvers import reverse
from django.template.context import RequestContext
from src.decorators import render_to
from src.problems.models import Category, Problem, Variant
from src.accounts.models import ChallengeResult


@render_to('challenge/index.html')
def index(request):
    categories = ''
    if 'challenge' in request.GET.keys() and (request.GET['challenge']=='kenguru' or request.GET['challenge']=='olimpiada'):
        ch = get_object_or_404(Category, slug=request.GET['challenge'])
        if 'category' in request.GET.keys() and not (request.GET['category']=='kenguru' or request.GET['category']=='olimpiada'):
            #выбраны категории, запускаем испытание
            cat = get_object_or_404(Category, slug=request.GET['category'])
            return HttpResponseRedirect(reverse('challenges:challenge', args=(cat.slug,)))
        else:
            categories = ch.get_children()
    return {'categories': categories}


def challenge_change(request):
    if request.is_ajax() and request.method == "GET" and 'challenge' in request.GET.keys():
        challenge = request.GET['challenge']
        categories = get_object_or_404(Category, slug=challenge).get_children()
        return render_to_response('challenge/_category_select.html',
                                  {'categories': categories},
                                  )
    else:
        raise Http404


def get_randoms(objects, count):
    res = []
    for i in range(count):
        obj = random.choice(objects)
        objects.remove(obj)
        res.append(obj)
    return res


def challenge(request, category_slug):
    cat = get_object_or_404(Category, slug=category_slug)
    if not cat.parent:
        raise Http404
    problems1, problems2, problems3 = (list(cat.problem_set.all().filter(slogn=1)), list(cat.problem_set.all().filter(slogn=2)), list(cat.problem_set.all().filter(slogn=3)))
    if cat.parent.slug == 'kenguru':
        if cat.slug == 'malysh_2' or cat.slug == 'malysh_34':
            problems = get_randoms(problems1, 10)+get_randoms(problems2, 10)+get_randoms(problems3, 5)
        else:
            problems = get_randoms(problems1, 10)+get_randoms(problems2, 10)+get_randoms(problems3, 10)
        return render_to_response('challenge/kenguru.html', {'problems':problems, 'category':cat}, context_instance=RequestContext(request))
    elif cat.parent.slug == 'olimpiada':
        problems = get_randoms(problems1, 2)+get_randoms(problems2, 2)+get_randoms(problems3, 1)
        return render_to_response('challenge/olimpiada.html', {'problems':problems, 'category':cat}, context_instance=RequestContext(request))
    else:
        raise Http404


def kenguru_check(request):
    if request.is_ajax():
        true_count, true_3, true_4, true_5, ball, true_problems, cb_result = (0, 0, 0, 0, 0, [], '')
        for k in request.POST.keys():
            if k == 'csrfmiddlewaretoken': continue
            answer = get_object_or_404(Variant, pk=int(request.POST[k]))
            if answer.tru:
                true_problems.append(answer.pro.pk)
                true_count += 1
                if answer.pro.slogn == 1:
                    true_3 += 1
                    ball += 3
                elif answer.pro.slogn == 2:
                    true_4 += 1
                    ball += 4
                elif answer.pro.slogn == 3:
                    true_5 += 1
                    ball += 5
            cat = answer.pro.category.slug
        if request.user.is_authenticated():
            category = get_object_or_404(Category, slug=cat)
            for cb in request.user.userprogress.challenge_best.all():
                if category == cb.category:
                    cb_result = cb.result
                    break
            try:
                oldres = request.user.userprogress.challenge_best.get(category=category)
                if oldres.result < ball:
                    oldres.result = ball
                    oldres.save()
            except:
                bestres = ChallengeResult(category=category,result=ball)
                bestres.save()
                request.user.userprogress.challenge_best.add(bestres)
        return render_to_response('challenge/_kenguru_res.html', {'true_count': true_count,
                                                                  'true_3': true_3,
                                                                  'true_4': true_4,
                                                                  'true_5': true_5,
                                                                  'ball': ball,
                                                                  'true_problems': true_problems,
                                                                  'cat': cat,
                                                                  'cb_result': cb_result})
    else:
        raise Http404


def olimpiada_check(request):
    if request.is_ajax():
        true_count, ball, true_problems, cb_result = (0, 0, [], '')
        for k in request.GET.keys():
            problem = get_object_or_404(Problem, pk=int(k[6:]))
            answer = request.GET[k]
            if answer == problem.answer:
                true_problems.append(problem)
                true_count += 1
                ball += 7
            cat = problem.category.slug
        if request.user.is_authenticated():
            category = get_object_or_404(Category, slug=cat)
            try:
                oldres = request.user.userprogress.challenge_best.get(category=category)
                if oldres.result < ball:
                    oldres.result = ball
                    oldres.save()
            except:
                bestres = ChallengeResult(category=category,result=ball)
                bestres.save()
                request.user.userprogress.challenge_best.add(bestres)
            for cb in request.user.userprogress.challenge_best.all():
                if category == cb.category:
                    cb_result = cb.result
                    break
        return render_to_response('challenge/_olimpiada_res.html', {'true_count': true_count,
                                                                  'ball': ball,
                                                                  'true_problems': true_problems,
                                                                  'cat': cat,
                                                                  'cb_result': cb_result})
    else:
        raise Http404

src/challenge/templates/challenge/_category_select.html
<div class="form-group" id="category-block">
    <label for="category-field" class="col-sm-4 control-label">Категория</label>
    <div class="col-sm-4">
        <select name="category" id="category-field" class="form-control" onchange="$('#challenge-start').show('easy')">
            {% for category in categories %}
                <option value="{{ category.slug }}">{{ category.title }}</option>
            {% endfor %}
        </select>
    </div>
</div>

src/challenge/templates/challenge/_kenguru_res.html
<div class="row">
    <div class="col-md-4">
        <div class="alert alert-success pull-left" style="height: 10px;margin-right: 10px">&nbsp</div> - решено правильно
        <div class="clearfix"></div>
    </div>
    <div class="col-md-7 col-md-offset-1">
        <div class="alert alert-error pull-left" style="height: 10px;margin-right: 10px">&nbsp</div> - решено неправильно или нерешено
    </div>
</div>
<hr>
<h3>Набрано {{ ball }} из {% if cat == 'malysh_2' or cat == 'malysh_34' %}95{% else %}120{% endif %} баллов&nbsp;
    {% if cb_result %}<small>наилучший результат - {{ cb_result }}</small>{% endif %}
</h3>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>Решено всего</th>
            <th>Задач в 3 балла</th>
            <th>Задач в 4 балла</th>
            <th>Задач в 5 баллов</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            {% if cat == 'malysh_2' or cat == 'malysh_34' %}
                <td>{{ true_count }}/25</td>
                <td>{{ true_3 }}/10</td>
                <td>{{ true_4 }}/10</td>
                <td>{{ true_5 }}/5</td>
            {% else %}
                <td>{{ true_count }}/30</td>
                <td>{{ true_3 }}/10</td>
                <td>{{ true_4 }}/10</td>
                <td>{{ true_5 }}/10</td>
            {% endif %}
        </tr>
    </tbody>
</table>
<script>
    $(function(){
        achievments_check();
        $('[id^="problem"]').addClass('alert alert-error');
        {% for pr in true_problems %}
            $('#problem{{ pr }}').removeClass('alert-error').addClass('alert-success');
        {% endfor %}
    });
</script>

src/challenge/templates/challenge/_olimpiada_res.html
<div class="row">
    <div class="col-md-4">
        <div class="alert alert-success pull-left" style="height: 10px;margin-right: 10px">&nbsp</div> - решено правильно
        <div class="clearfix"></div>
    </div>
    <div class="col-md-7 col-md-offset-1">
        <div class="alert alert-error pull-left" style="height: 10px;margin-right: 10px">&nbsp</div> - решено неправильно или нерешено
    </div>
</div>
<hr>
<h3>Набрано {{ ball }} из 35 баллов&nbsp;
    {% if cb_result %}<small>наилучший результат - {{ cb_result }}</small>{% endif %}
</h3>
<h3>Решено {{ true_count }} из 5 задач.</h3>
<script>
    $(function(){
        achievments_check();
        $('[id^="problem"]').addClass('alert alert-error');
        {% for pr in true_problems %}
            $('#problem{{ pr.pk }}').removeClass('alert-error').addClass('alert-success');
        {% endfor %}
    });
</script>

src/challenge/templates/challenge/challenge.html
{% extends 'problems/base_problems.html' %}

{% block title %}Испытание {{ category.parent.title }} - {{ category.title }}{% endblock %}

{% block content_problem %}
    <h4>Испытание {{ category.parent.title }} - {{ category.title }}</h4>
    {% for problem in problems %}
        {{ problem.text|safe }}<hr>
    {% endfor %}
{% endblock %}

src/challenge/templates/challenge/index.html
{% extends 'problems/base_problems.html' %}
{% load bootstrap %}

{% block title %}Выбор испытания{% endblock %}

{% block page_desc %}Конкурс Кенугуру, математические олимпиады онлайн{% endblock %}

{% block content_problem %}
    <p class="text-muted">
        В режиме испытания задачи подбираются случайным образом так, чтобы максимально соответствовать реальному конкурсу.
        Достигается это благодаря алгоритму, который выбирает задачи нужной категории и сложности.
    </p>
    <form method="get" action="." class="form-horizontal">
        <div class="form-group">
            <label for="challenge-field" class="col-sm-4 control-label">Выберите испытание</label>
            <div class="col-sm-4">
                <select name="challenge" id="challenge-field" class="form-control" onchange="challenge_change(this.value)">
                    <option selected="selected" disabled="disabled">----------</option>
                    <option value="kenguru"{% if categories and request.get_full_path == '/challenge/?challenge=kenguru' %}selected="selected" {% endif %}>Кенгуру</option>
                    <option value="olimpiada"{% if categories and request.get_full_path == '/challenge/?challenge=olimpiada' %}selected="selected" {% endif %}>Олимпиада</option>
                </select>
            </div>
        </div>
        <div id="target">
            {% if categories %}
                <div class="form-group" id="category-block">
                    <label for="category-field" class="col-sm-4 control-label">Категория</label>
                    <div class="col-sm-4">
                        <select name="category" id="category-field" class="form-control" onchange="$('#challenge-start').show('easy')">
                            {% for category in categories %}
                                <option value="{{ category.slug }}">{{ category.title }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
            {% endif %}
        </div>
        <div class="form-group">
            <div class="col-sm-4 col-sm-offset-4">
                <button id="challenge-start" type="submit" class="btn btn-success" {% if not categories %}style="display: none"{% endif %}>Начать</button>
            </div>
        </div>
    </form>

    <script>
        function challenge_change(challenge) {
            $('#category-block').removeClass('hide');
            $.ajax({
                type: 'GET',
                url: '/challenge/challenge_change/',
                data: {'challenge': challenge},
                success: function (html) {
                    $('#target').html(html);
                    $('#challenge-start').show('easy');
                }
            });
        }
    </script>
{% endblock %}

src/challenge/templates/challenge/kenguru.html
{% extends 'problems/base_problems.html' %}

{% block title %}Испытание Кенгуру - {{ category.title }}{% endblock %}

{% block head %}
    <script src="/static/js/challenges/kenguru.js"></script>
{% endblock %}

{% block page_desc %}
    Подготовка к конкурсу Кенгуру онлайн, пробный конкурс Кенгуру.
{% endblock %}

{% block content_problem %}
    <div class="row">
        <div class="col-md-12">
            <h3>Испытание Кенгуру - {{ category.title }}</h3>
            <form method="post" id="answer_form">{% csrf_token %}
            {% for problem in problems %}
                <div class="challenge_problem" id="pr{{ forloop.counter }}">
                    <div id="problem{{ problem.pk }}"><strong>{{ forloop.counter }}</strong>. {{ problem.text|safe }}<br></div>
                    <div class="kenguru-answer-form">
                            <input class="radio radio-inline" type="radio" name="answer{{ problem.pk }}" value="{{ problem.variant_set.all.0.pk }}">({{ problem.variant_set.all.0.nam }})&nbsp;{{ problem.variant_set.all.0.val|safe }}
                            <input class="radio radio-inline" type="radio" name="answer{{ problem.pk }}" value="{{ problem.variant_set.all.1.pk }}">({{ problem.variant_set.all.1.nam }})&nbsp;{{ problem.variant_set.all.1.val|safe }}
                            <input class="radio radio-inline" type="radio" name="answer{{ problem.pk }}" value="{{ problem.variant_set.all.2.pk }}">({{ problem.variant_set.all.2.nam }})&nbsp;{{ problem.variant_set.all.2.val|safe }}
                            <input class="radio radio-inline" type="radio" name="answer{{ problem.pk }}" value="{{ problem.variant_set.all.3.pk }}">({{ problem.variant_set.all.3.nam }})&nbsp;{{ problem.variant_set.all.3.val|safe }}
                            <input class="radio radio-inline" type="radio" name="answer{{ problem.pk }}" value="{{ problem.variant_set.all.4.pk }}">({{ problem.variant_set.all.4.nam }})&nbsp;{{ problem.variant_set.all.4.val|safe }}
                    </div>
                    <hr>
                </div>
            {% endfor %}
            </form>
            <div id="button_res">
                <button class="btn btn-success" id="answerButton">Отправить на проверку</button>
            </div>
            <div id="timer"></div>
            <div id="target"></div>
        </div>
    </div>
{% endblock %}

src/challenge/templates/challenge/olimpiada.html
{% extends 'problems/base_problems.html' %}

{% block title %}Испытание Олимпиада - {{ category.title }}{% endblock %}

{% block page_desc %}
    Подготовка к математической олимпиаде онлайн, пробные олимпиады по математике.
{% endblock %}

{% block head %}
    <script src="/static/js/challenges/olimpiada.js"></script>
{% endblock %}

{% block content_problem %}
    <div class="row">
        <div class="col-md-12">
            <h3 class="margin-bottom-20">Испытание Олимпиада - {{ category.title }}</h3>
            <form method="post" id="answer_form">
                {% for problem in problems %}
                    <div class="row">
                        <div class="col-md-8">
                            <div id="problem{{ problem.pk }}"><strong>{{ forloop.counter }}</strong>. {{ problem.text|safe }}<br></div>
                        </div>
                        <div class="col-md-4 olimpiada-answer-form">
                            <div class="input-group">
                                <span class="input-group-addon">Ответ:</span>
                                <input class="form-control" type="text" name="answer{{ problem.pk }}">
                            </div>
                        </div>
                    </div>
                    <hr>
                {% endfor %}
            </form>
            <p class="italic text-right">Все задачи оцениваются в 7 баллов.</p>
            <div id="button_res" class="margin-bottom-20">
                <button class="btn btn-success" id="answerButton">Отправить на проверку</button>
            </div>
            <div id="timer"></div>
            <div id="target"></div>
            <small class="text-muted">Во время проведения реальной олимпиады по математике оценивается всё решение,
                его полнота. По-этому и оценка может быть от 0 до 7 баллов. К сожалению, здесь мы можем проверить лишь
                правильность ответа. Соответственно, оценка может быть или 0, или 7 баллов.
            </small>
        </div>
    </div>
{% endblock %}