src/lessons/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, url


urlpatterns = patterns('src.lessons.views',
    url(r'^$', 'index', name='index'),
    url(r'^(?P<theme_pk>\d+)/$', 'theme', name='theme'),
    url(r'^(?P<theme_pk>\d+)/lesson/(?P<lesson_number>\d+)/$', 'lesson', name='lesson'),
    url(r'^check/$', 'answer_check'),
)

src/urls.py
# -*- coding: utf-8

from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'', include('social_auth.urls')),
    url(r'^', include('src.main.urls', 'main')),
    url(r'^admin/', include(admin.site.urls)),
    # url(r'^lessons/', include('src.lessons.urls', 'lessons')),
    url(r'^problems/', include('src.problems.urls', 'problems')),
    url(r'^auth/', include('src.accounts.urls', 'accounts')),
    url(r'^achievments/', include('src.achievments.urls', 'achievments')),
    url(r'^challenge/', include('src.challenge.urls', 'challenges')),
    url(r'^game/', include('src.games.urls', 'games')),
)+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/lessons/models.py
# -*- coding: utf-8 -*-

from django.db import models


class Theme(models.Model):
    title = models.CharField(verbose_name=u'Название темы', max_length=150)
    description = models.TextField(verbose_name=u'Описание', blank=True)
    klass = models.IntegerField(verbose_name=u'Класс')
    sort_number = models.IntegerField(u'Номер темы по списку')
    complit_count = models.IntegerField(u'Количество прошедших', default=0)

    class Meta:
        verbose_name = u'Тема'
        verbose_name_plural = u'Темы'

    def __unicode__(self):
        return self.title


class Lesson(models.Model):
    theme = models.ForeignKey(Theme, verbose_name=u'Тема')
    number = models.IntegerField(verbose_name=u'Номер урока')
    title = models.CharField(verbose_name=u'Название', max_length=150)
    material = models.TextField(verbose_name=u'Учебный материал')
    test = models.BooleanField(verbose_name=u'Контрольная работа', default=False)


    class Meta:
        verbose_name = u'Урок'
        verbose_name_plural = u'Уроки'

    def __unicode__(self):
        return self.title


class Task(models.Model):
    lesson = models.ForeignKey(Lesson, verbose_name=u'Урок')
    text = models.TextField(verbose_name=u'Текст задания')
    answer = models.CharField(verbose_name=u'Ответ', max_length=150)
    slog = models.IntegerField(verbose_name=u'Сложность',
                               help_text=u'От 1 до 3', default='1')

    class Meta:
        verbose_name = u'Задание'
        verbose_name_plural = u'Задания'

    def __unicode__(self):
        return self.text[:20]


class Remember(models.Model):
    title = models.CharField(verbose_name=u'Заголовок', max_length=150, blank=True)
    text =models.TextField(verbose_name=u'Текст')
    lesson = models.ForeignKey(Lesson, verbose_name=u'К уроку...')

    class Meta:
        verbose_name = u'Запоминалка'
        verbose_name_plural = u'Запоминалки'

    def __unicode__(self):
        return self.title

src/lessons/forms.py
# -*- coding: utf-8 -*-

from django import forms

from . models import Task


class AnswerForm(forms.Form):
    answer = forms.CharField()
    answer.widget.attrs.update({
        'class': 'form-control',
        'placeholder': u'Ответ',
        'onkeydown': "javascript:if(13==event.keyCode){return false;}"
    })

src/lessons/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import get_object_or_404
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse

from src.decorators import render_to
from . models import Theme, Task, Lesson
from . forms import AnswerForm


@render_to('lessons/index.html')
def index(request):
    themes = [[i + 5, Theme.objects.filter(klass=(i+5))] for i in range(7)]
    return {'themes': themes,}


@render_to('lessons/theme.html')
def theme(request, theme_pk):
    theme = get_object_or_404(Theme, pk=theme_pk)
    return {'theme': theme}


@render_to('lessons/lesson.html')
def lesson(request, theme_pk, lesson_number):
    form = AnswerForm()
    if request.method == 'POST':
        form = AnswerForm(request.POST)
    theme = get_object_or_404(Theme, pk=theme_pk)
    lesson_count = len(theme.lesson_set.all())
    try:
        lesson = theme.lesson_set.get(number=lesson_number)
    except:
        lesson = theme.lesson_set.all().order_by('number')[lesson_count-1]
    tasks = lesson.task_set.all().order_by('slog')
    return {'theme': theme, 'lesson': lesson, 'tasks': tasks, 'form': form}


def answer_check(request):
    if request.is_ajax() and request.method == "POST":
        data = False
        task_pk = request.POST['task_pk']
        ans = request.POST['answer']
        task = get_object_or_404(Task, pk=task_pk)
        if ans == task.answer:
            data = True
            if request.user.is_authenticated():
                request.user.userprogress.lessons_solved_tasks.add(task)

                less = task.lesson
                lesson_complit = True
                for t in less.task_set.all():
                    if not t in request.user.userprogress.lessons_solved_tasks.all():
                        lesson_complit = False
                        break
                if lesson_complit:
                    request.user.userprogress.lessons_solved_lessons.add(less)
                    th = less.theme
                    theme_complit = True
                    request.user.userprogress.lessons_solved_tasks = ''
                    for l in th.lesson_set.all():
                        if not l in request.user.userprogress.lessons_solved_lessons.all():
                            theme_complit = False
                            break
                    if theme_complit:
                        request.user.userprogress.lessons_solved_themes.add(th)
                        data = 'theme_complit'
        return HttpResponse(data)
    else:
        raise Http404

src/lessons/templates/lessons/index.html
{% extends 'base.html' %}

{% block title %}Уроки математики{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                {% if not user.is_authenticated %}
                    <div class="alert alert-danger">
                        <a href="{% url 'accounts:login' %}?next={{ request.path }}">Авторизуйтесь</a>, чтобы сохранять прогресс прохождения уроков
                        и отслеживать свои результаты.
                    </div>
                {% endif %}
            {% for th in themes %}{% if th.1 %}
                <div class="panel panel-default">
                    <div class="panel-heading"><strong>{{ th.0 }} класс</strong></div>
                    <table class="table table-bordered">
                        <tbody>
                        {% for theme in th.1 %}
                            <tr>
                                <td style="width: 20%"><strong><a href="{% url 'lessons:theme' theme.pk %}">{{ theme.title }}</a></strong></td>
                                <td>{{ theme.description|safe }}</td>
                                <td class="table_button_column">
                                    {% if user.is_authenticated and theme in user.userprogress.lessons_solved_themes.all %}
                                        <div class="label label-success">пройден</div>
                                    {% else %}
                                        <div class="label label-primary">доступен</div>
                                    {% endif %}
                                </td>
                                <td class="table_button_column">
                                    <a href="{% url 'lessons:lesson' theme.pk 1 %}" class="btn btn-block btn-warning">Пройти</a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            {% endif %}{% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

src/lessons/templates/lessons/lesson.html
{% extends 'base.html' %}
{% load lessons_tags %}

{% block title %}{{ lesson.title }} - {{ theme.title }}{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h3>{{ lesson.title }} <small>({{ lesson.number }}/{{ theme.lesson_set.all|length }})</small></h3>
                <div class="row">
                    <div class="col-md-9">
                        <div class="material">
                            {{ lesson.material|safe }}
                        </div>
                    </div>
                    {% if lesson.remember_set.all %}
                        <div class="col-md-3 well">
                            <div class="remember_title">Запомни</div>
                            {% for rememb in lesson.remember_set.all %}
                                <h5>{{ rememb.title }}</h5>
                                {{ rememb.text|safe }}
                                {% if not forloop.last %}<hr>{% endif %}
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>

                <h4>Задания</h4>
                <div class="text-muted margin-bottom-20">Выполни все задания для успешного прохождения урока.</div>
                {% for task in tasks %}
                    <div class="row">
                        <div class="col-md-1 text-center">
                            <span class="badge {{ task.slog|slog_color }}">&nbsp;</span>
                        </div>
                        <div class="col-md-8">
                            {{ task.text|safe }}
                        </div>
                        <div class="col-md-3">
                            <form class="form-inline" role="form" method="post">{% csrf_token %}
                                <div class="form-group">
                                    {{ form.answer }}
                                    <input type="hidden" name="task_pk" value="{{ task.pk }}">
                                </div>
                                <button type="button" id="answer_{{ task.pk }}" class="btn btn-primary"><i class="fa fa-question"></i></button>
                            </form>
                        </div>
                    </div>
                    {% if not forloop.last %}<hr>{% endif %}
                {% endfor %}
                <div class="col-md-3 col-md-offset-9">
                    <a class="btn btn-success btn-block margin-top-20"
                       id="next_challenge" style="display: none" href="{% url 'lessons:lesson' theme.pk lesson.number|add:"1" %}">Следующий урок</a>
                </div>
                </div>
            </div>
        </div>
{% endblock %}

{% block scripts %}
    <script>
        $(document).ready(function () {
            $("input").blur(function() {
                var this_input = $(this);
                var task_pk = $(this).next('input').attr('value');
                var div_out_id = '#answer_' + task_pk;
                var form = $(div_out_id).parents('form');
                var msg   = form.serialize();

                function redirect() {
                    location = "{% url 'lessons:theme' theme.pk %}";
                }

                function suc(data) {
                    $(div_out_id).removeClass('btn-primary btn-success btn-danger');
                    if (data == 'theme_complit') {
                        $(div_out_id).html('<i class="fa fa-check">');
                        $(div_out_id).addClass('btn-success');
                        this_input.attr('disabled', true);
                        setTimeout(redirect, 1000);
                    } else {
                        if (data == 'True') {
                            $(div_out_id).html('<i class="fa fa-check">');
                            $(div_out_id).addClass('btn-success');
                            this_input.attr('disabled', true);
                            if (document.getElementsByClassName('fa-check').length == {{ tasks|length }}) {
                                $('#next_challenge').show("slow");
                            }
                            achievments_check();
                        } else {
                            $(div_out_id).html('<i class="fa fa-times">');
                            $(div_out_id).addClass('btn-danger');
                        }
                    }
                }

                $.ajax({
                    type: 'POST',
                    data: msg,
                    url: '/lessons/check/',
                    beforeSend: function() { $(div_out_id).html('...'); },
                    success: suc,
                    error: function () {$(div_out_id).html('err')}
                })
            });
        });
    </script>
{% endblock %}

src/lessons/templates/lessons/theme.html
{% extends 'base.html' %}

{% block title %}{{ theme.klass }} класс, {{ theme.title }}{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading"><strong>Тема {{ theme.title }}</strong></div>
                    <div class="panel-body">{{ theme.description|safe }}</div>
                    <table class="table table-bordered">
                        {% for lesson in theme.lesson_set.all %}
                            <tr>
                                <td>Урок {{ forloop.counter }}. <a href="{% url 'lessons:lesson' theme.pk lesson.number %}">{{ lesson.title }}</a></td>
                                <td class="table_button_column">
                                    {% if user.is_authenticated and lesson in user.userprogress.lessons_solved_lessons.all %}
                                        <div class="label label-success">пройден</div>
                                    {% else %}
                                        <div class="label label-primary">доступен</div>
                                    {% endif %}
                                </td>
                                <td class="text-center table_button_column">
                                    <a href="{% url 'lessons:lesson' theme.pk lesson.number %}" class="btn btn-block btn-warning">Пройти</a>
                                </td>
                            </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script>
        achievments_check();
    </script>
{% endblock %}